# 8 Exercises

In [3]:
import numpy as np
# Use the following code for the questions below:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [9]:
# 1. How many negative numbers are there?
negatives = a < 0
len(a[negatives])

4

In [10]:
# 2. How many positive numbers are there?
positives = a >= 0
len(a[positives])

8

In [11]:
# 3. How many even positive numbers are there?
positive_even = (a >= 0) & (a % 2 == 0)
len(a[positive_even])

6

In [19]:
# 4. If you were to add 3 to each data point, how many positive numbers would there be?
add_3 = a + 3
len(add_3[add_3 >= 0])

10

In [26]:
# 5. If you squared each number, what would the new mean and standard deviation be?
sqr = a ** 2
print('old mean ==>',np.mean(a))
print('new mean ==>',np.mean(sqr))
print('old std ==>',np.std(a))
print('new std ==>',np.std(sqr))

old mean ==> 3.0
new mean ==> 74.0
old std ==> 8.06225774829855
new std ==> 144.0243035046516


In [32]:
# 6. A common statistical operation on a dataset is centering. This means to adjust the data such 
#    that the mean of the data is 0. This is done by subtracting the mean from each data point. 
#    Center the data set. See this link for more on centering.
np.mean(a)
center_array = a - np.mean(a)
center_array

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [35]:
# 7. Calculate the z-score for each data point. Recall that the z-score is given by:
a_meansub = a - np.mean(a)
a_zscore = a_meansub / np.std(a)
a_zscore

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [36]:
# 8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py 
#    and add your solutions.

# 8's Setup 1 (8)

In [37]:
import numpy as np
# Life w/o numpy to life with numpy

In [44]:
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [45]:
# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_a = np.sum(a)
sum_of_a

55

In [46]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a = np.min(a)
min_of_a

1

In [47]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = np.max(a)
max_of_a

10

In [48]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = np.mean(a)
mean_of_a

5.5

In [49]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in 
#              the above list together
product_of_a = np.product(a)
product_of_a

3628800

In [51]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like 
#              [1, 4, 9, 16, 25...]
squares_of_a = np.square(a)
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [56]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
array_a = np.array(a)
odds_in_a = array_a[array_a % 2 != 0]
odds_in_a

array([1, 3, 5, 7, 9])

In [57]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a = array_a[array_a % 2 == 0]
evens_in_a

array([ 2,  4,  6,  8, 10])

# 8's Setup 2 (12)

In [58]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of 
#           squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [66]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first 
#              need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

# Array version
sum_of_b
array_b = np.array(b)
sum_of_array_b = np.sum(array_b)
sum_of_array_b

33

In [68]:
# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])

# Array version
min_of_array_b = np.min(array_b)
min_of_array_b

3

In [69]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

# Array Version
max_of_array_b = np.max(array_b)
max_of_array_b

8

In [70]:
# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

# Array Version
mean_of_array_b = np.mean(array_b)
mean_of_array_b

5.5

In [71]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied 
#              together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

# Array Version
product_of_array_b = np.product(array_b)
product_of_array_b

20160

In [73]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
        
# Array Version
squares_of_array_b = np.square(array_b)
squares_of_array_b

array([[ 9, 16, 25],
       [36, 49, 64]])

In [74]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
            
# Array Version
odds_in_array_b = array_b[array_b % 2 != 0]
odds_in_array_b

array([3, 5, 7])

In [75]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
            
# Array Version
evens_in_array_b = array_b[array_b % 2 == 0]
evens_in_array_b

array([4, 6, 8])

In [76]:
# Exercise 9 - print out the shape of the array b.
array_b.shape

(2, 3)

In [77]:
# Exercise 10 - transpose the array b.
array_b.transpose

<function ndarray.transpose>

In [78]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
array_b.reshape(1, 6)

array([[3, 4, 5, 6, 7, 8]])

In [79]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
array_b.reshape(6, 1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

# 8's Setup 3 (8)

In [5]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy 
#       array methods.

In [ ]:
# Exercise 1 - Find the min, max, sum, and product of c.


In [ ]:
# Exercise 2 - Determine the standard deviation of c.


In [ ]:
# Exercise 3 - Determine the variance of c.


In [ ]:
# Exercise 4 - Print out the shape of the array c


In [ ]:
# Exercise 5 - Transpose c and print out transposed result.


In [ ]:
# Exercise 6 - Get the dot product of the array c with c. 


In [ ]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261


In [ ]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer 
#              should be 131681894400.


# 8's Setup 4 (10)

In [6]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

In [ ]:
# Exercise 1 - Find the sine of all the numbers in d


In [ ]:
# Exercise 2 - Find the cosine of all the numbers in d


In [ ]:
# Exercise 3 - Find the tangent of all the numbers in d


In [ ]:
# Exercise 4 - Find all the negative numbers in d


In [ ]:
# Exercise 5 - Find all the positive numbers in d


In [ ]:
# Exercise 6 - Return an array of only the unique numbers in d.


In [ ]:
# Exercise 7 - Determine how many unique numbers there are in d.


In [ ]:
# Exercise 8 - Print out the shape of d.


In [ ]:
# Exercise 9 - Transpose and then print out the shape of d.


In [ ]:
# Exercise 10 - Reshape d into an array of 9 x 2


# Awesome Bonus

For much more practice with numpy, Go to https://github.com/rougier/numpy-100 
and clone the repo down to your laptop. To clone a repository: - Copy the SSH 
address of the repository - 
cd ~/codeup-data-science - Then type git clone git@github.com:rougier/numpy-100.git - 
Now do cd numpy-100 on your terminal. - Type 
git remote remove origin, so you won't accidentally try to push your work to Rougier's repo.

Congratulations! You have cloned Rougier's 100 numpy exercises to your computer. Now you need to 
make a new, blank, repository on GitHub.

       - Go to https://github.com/new to make a new repo. Name it numpy-100.
       - DO NOT check any check boxes. We need a blank, empty repo.
       - Finally, follow the directions to "push an existing repository from the command line" so 
         that you can push up your changes to your own account.
       - Now do work, add it, commit it, and push it!