# Numpy

https://numpy.org/

## What is it? 
- Numpy is a Python library used for working with arrays
- Numpy is the fundamental package for scientific computing in Python


## Why do we care? 
- Numpy is one of the main reasons why Python is so powerful and popular for scientific computing
- Super fast. Numpy arrays are implemented in C, which makes numpy very fast.
- The arrays allows for vectorized operations

## Show us! 

### Create a 1D array

#### create a list
format: list()

In [1]:
#create a list
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

In [2]:
#whats the type
type(my_list)

list

In [3]:
#what is dtype used for arrays
my_list.dtype

AttributeError: 'list' object has no attribute 'dtype'

In [4]:
#whats the shape used for arrays
list.shape

AttributeError: type object 'list' has no attribute 'shape'

#### create an array
format: np.array()

In [5]:
#import numpy
import numpy as np

In [7]:
#create the array
my_array = np.array(my_list)

In [8]:
#whats the type
type(my_array)

numpy.ndarray

In [9]:
#whats the shape
my_array.shape

(4,)

In [11]:
#whats the dtype
my_array.dtype

dtype('int64')

#### access elements of our new array

In [12]:
my_array

array([1, 2, 3, 4])

In [13]:
my_array[0] #calling the first index, which is zero

1

In [14]:
my_array[-1] #calling the last index, which is four

4

#### slice the array

In [15]:
my_array[1:] #inclusive for the first element

array([2, 3, 4])

In [16]:
my_array[:-2] #exclusive for the second from last element

array([1, 2])

#### create an array from 1 to 100

In [18]:
#np.array(?)
a = np.array(range(1, 101))
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [19]:
#access single element
a[0]

1

In [20]:
a[-1]

100

In [21]:
#slice the array! 
a[25:]

array([ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [22]:
a[5:15]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### Create a 2D array

In [24]:
#build a list of lists
matrix = [[1,2,3],
[2,3,4],
[6,7,8]]
matrix

[[1, 2, 3], [2, 3, 4], [6, 7, 8]]

In [25]:
type(matrix)

list

In [27]:
#turn it into an array! 
matrix_array = np.array(matrix)
matrix_array

array([[1, 2, 3],
       [2, 3, 4],
       [6, 7, 8]])

In [28]:
#type
type(matrix_array)

numpy.ndarray

#### access elements

In [31]:
matrix_array[0] #1st list in outer list

array([1, 2, 3])

In [32]:
matrix_array[-1] #Last list in outer list

array([6, 7, 8])

In [33]:
matrix_array[0, 0] #1st element in nested list in outer list

1

In [34]:
matrix_array[2, 1]

7

### Descriptive Stats

In [35]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

#### using methods: the method is called on the numpy object

### format: object.method()

In [36]:
a.min()

1

In [37]:
a.max()

100

In [38]:
a.std(), a.mean()

(28.86607004772212, 50.5)

In [39]:
a.sum()

5050

#### using functions: using numpy to call functions

In [40]:
max(a)

100

In [213]:
np.max(a)

100

In [214]:
np.std(a)

28.86607004772212

In [215]:
np.mean(a)

50.5

In [216]:
np.sum(a)

5050

In [41]:
np.mean(matrix_array)

4.0

In [ ]:
np.max(matrix_array)

### Array of Booleans! 

### Boolean Masks

1. create an array
2. make a list of booleans (mask)
3. combine

    format: array [ list of booleans ] 

In [42]:
#pull back our small array
my_array

array([1, 2, 3, 4])

In [43]:
#make list of booleans aka our mask
mask = [True, False, False, True]
mask

[True, False, False, True]

In [44]:
#combine them 
my_array[mask]

array([1, 4])

In [ ]:
# > only return values that are true. this is known as boolean masking

#### how else can we get our array of boolean values?

In [45]:
my_array

array([1, 2, 3, 4])

In [50]:
#write a conditional with the array
mask = my_array == 4
mask

array([False, False, False,  True])

In [51]:
my_array[mask]

array([4])

In [52]:
mask = my_array > 2
mask

array([False, False,  True,  True])

In [53]:
my_array[mask]

array([3, 4])

In [54]:
my_array == 2 or my_array == 4

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### make and apply our boolean mask

array([False, False, False,  True, False])

In [485]:
#format: array_name [ list_of_booleans ]


In [55]:
matrix_array

array([[1, 2, 3],
       [2, 3, 4],
       [6, 7, 8]])

### Do it with a matrix!

In [56]:
mask = (matrix_array > 3)
mask

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [57]:
matrix_array[mask]

array([4, 6, 7, 8])

### what about with multiple conditions?

In [58]:
mask = (my_array == 2) | (my_array == 4)
mask

array([False,  True, False,  True])

In [59]:
my_array[mask]

array([2, 4])

#### cool! can we just do it with a list instead of an array?

In [60]:
#pull back our initial list
my_list

[1, 2, 3, 4]

In [61]:
#create a array of booleans
my_list == 4

False

In [62]:
#apply an array of booleans to a list
my_list[mask]

TypeError: only integer scalar arrays can be converted to a scalar index

#### let's bring it back to arrays and make them bigger

In [63]:
#array
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [65]:
#mask
mask = (a >= 90)
mask

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [66]:
#boolean mask
a[mask]

array([ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

#### shortcut?

In [67]:
a[a >= 90]

array([ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [68]:
a[(a >= 50) & (a % 2 == 0)]

array([ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,
        76,  78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

#### what if we wanted to check two conditions?

In [70]:
# note the parenthesis
# also note that we're using & instead of and
mask = (a > 5) & (a < 15)
a[mask]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

#### what if we wanted the opposite of our mask?

In [72]:
~mask

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [73]:
# the ~ notates the opposite of
a[~mask]

array([  1,   2,   3,   4,   5,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

## Vectorization Operations
- makes looping over math so easy and fast!

### Add one to every element

#### hard way: doing it in a list

In [74]:
my_list

[1, 2, 3, 4]

In [80]:
#using a for loop
new_list = []

for x in my_list:
    print(x + 1)
    new_list.append(x + 1)
new_list

2
3
4
5


[2, 3, 4, 5]

In [82]:
#using a list comprehension
new_list = ([x + 1 for x in my_list])
new_list

[2, 3, 4, 5]

#### easy way: doing it with an array

In [83]:
my_array

array([1, 2, 3, 4])

In [84]:
#using vectorization operations
my_array + 1

array([2, 3, 4, 5])

### more operations

### show us the speed

In [87]:
#make a really big array
big_array = np.array(range(1000000))
big_array

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [96]:
%%timeit

big_array ** 2

602 µs ± 20.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [94]:
#make a really big list
big_list = list(big_array)
big_list[:10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [97]:
%%timeit

for x in big_list:
    x**2

140 ms ± 1.84 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Numpy ways to create arrays

#### full of zeros

In [101]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [102]:
np.zeros((10)) + 1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [100]:
np.zeros((10, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

#### full of ones

In [104]:
np.ones(5)

array([1., 1., 1., 1., 1.])

#### full of whatever you want 

In [106]:
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

#### a quicker way to make a range

In [107]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### an array of random integers

In [115]:
#np.random.randint()
np.random.randint(2, 20, 10)

array([18,  7,  4,  3, 16, 10, 12, 17,  6,  9])

In [116]:
np.random.randint(-1, 10, 21)

array([5, 2, 4, 2, 4, 0, 9, 3, 3, 5, 0, 3, 7, 2, 4, 4, 1, 5, 9, 6, 3])

#### an array of random numbers from the standard distribution

In [123]:
#np.random.randn()
np.random.randn(10)

array([ 1.40133335,  0.77008663,  0.6804425 ,  0.61047834,  1.35376849,
       -0.87828845, -1.20553145, -0.40793069,  0.64042465,  0.27651165])